var json = '{
  "layoutOptions": {
    "hideButtons": true
  },
  "cards" : [ 
     { "id" : "Q001", "text" : "Easily adjust to shifting priorities", "dimension" : "ADAPTABILITY" },
     { "id" : "Q002", "text" : "Sometimes, I\'m slow to adopt new ideas", "dimension" : "ADAPTABILITY" },
     { "id" : "Q003", "text" : "Occasionally, I find it hard to adjust to a new work environment", "dimension" : "ADAPTABILITY" },
     { "id" : "Q004", "text" : "I adjust to a new team as quickly as the average person", "dimension" : "ADAPTABILITY" },
     { "id" : "Q005", "text" : "I am usually open to input from others", "dimension" : "ADAPTABILITY" },
     { "id" : "Q006", "text" : "I try to create innovative solutions, unless the typical solution is still the best approach", "dimension" : "ADAPTABILITY" },
     { "id" : "Q007", "text" : "Constantly seek to improve tried-and-true processes", "dimension" : "ADAPTABILITY" },
     { "id" : "Q008", "text" : "Prefer a predictable workflow", "dimension" : "ADAPTABILITY" },
     { "id" : "Q009", "text" : "Get excited about change as much as the average person", "dimension" : "ADAPTABILITY" },
     { "id" : "Q010", "text" : "My ideal job would include some unstructured tasks, and others that are routine", "dimension" : "ADAPTABILITY" },
     { "id" : "Q011", "text" : "I would rather try something new than do something I\'ve done before", "dimension" : "ADAPTABILITY" },
     { "id" : "Q012", "text" : "Avoid situations that require me to try new things", "dimension" : "ADAPTABILITY" },
     { "id" : "Q013", "text" : "Tend to set goals of average difficulty", "dimension" : "AMBITION" },
     { "id" : "Q014", "text" : "If I really want something I\'ll push myself to achieve it", "dimension" : "AMBITION" },
     { "id" : "Q015", "text" : "Openly compete with others for opportunities", "dimension" : "AMBITION" },
     { "id" : "Q016", "text" : "I am focused on achieving success", "dimension" : "AMBITION" },
     { "id" : "Q017", "text" : "Prefer to have work-life balance", "dimension" : "AMBITION" },
     { "id" : "Q018", "text" : "Am content with seeing where my career takes me", "dimension" : "AMBITION" },
     { "id" : "Q019", "text" : "Care about my career, but that\'s not all there is to life", "dimension" : "AMBITION" },
     { "id" : "Q020", "text" : "Have ambitious goals, but some of them are more attainable than others", "dimension" : "AMBITION" },
     { "id" : "Q021", "text" : "I sometimes speak with others about my career goals", "dimension" : "AMBITION" },
     { "id" : "Q022", "text" : "Am always thinking about how to advance my career", "dimension" : "AMBITION" },
     { "id" : "Q023", "text" : "Care about winning only when competing against someone I dislike", "dimension" : "AMBITION" },
     { "id" : "Q024", "text" : "Set ambitious career goals most of the time", "dimension" : "AMBITION" },
     { "id" : "Q025", "text" : "Don\'t care if I don\'t get a promotion I deserve", "dimension" : "AMBITION" },
     { "id" : "Q026", "text" : "Hold back my opinions", "dimension" : "ASSERTIVENESS" },
     { "id" : "Q027", "text" : "Sometimes I readily share my ideas", "dimension" : "ASSERTIVENESS" },
     { "id" : "Q028", "text" : "Sometimes I share my ideas, especially if I really believe in them", "dimension" : "ASSERTIVENESS" },
     { "id" : "Q029", "text" : "I often share my opinions even if they are unpopular", "dimension" : "ASSERTIVENESS" },
     { "id" : "Q030", "text" : "Rarely do I push for my own ideas", "dimension" : "ASSERTIVENESS" },
     { "id" : "Q031", "text" : "Have been said to speak aggressively on occasion", "dimension" : "ASSERTIVENESS" },
     { "id" : "Q032", "text" : "Can be submissive when talking with coworkers I don\'t know", "dimension" : "ASSERTIVENESS" },
     { "id" : "Q033", "text" : "Persuade others as much as anyone else", "dimension" : "ASSERTIVENESS" },
     { "id" : "Q034", "text" : "Coworkers sometimes listen to what I have to say", "dimension" : "ASSERTIVENESS" },
     { "id" : "Q035", "text" : "Almost always say what I\'m thinking", "dimension" : "ASSERTIVENESS" },
     { "id" : "Q036", "text" : "Can usually persuade others to my point of view", "dimension" : "ASSERTIVENESS" },
     { "id" : "Q037", "text" : "Rarely voice my opinions", "dimension" : "ASSERTIVENESS" },
     { "id" : "Q038", "text" : "I enjoy being a part of a team", "dimension" : "COLLABORATION" },
     { "id" : "Q039", "text" : "Like to work in solitude", "dimension" : "COLLABORATION" },
     { "id" : "Q040", "text" : "Facilitate team brainstorming as much as the average person", "dimension" : "COLLABORATION" },
     { "id" : "Q041", "text" : "I often prefer to work on projects with others", "dimension" : "COLLABORATION" },
     { "id" : "Q042", "text" : "Like projects where everyone offers their input", "dimension" : "COLLABORATION" },
     { "id" : "Q043", "text" : "Try to make sure everyone\'s voice is heard on a project", "dimension" : "COLLABORATION" },
     { "id" : "Q044", "text" : "When given the choice, I\'d prefer to work with others than by myself", "dimension" : "COLLABORATION" },
     { "id" : "Q045", "text" : "Like working as a part of a team about half the time", "dimension" : "COLLABORATION" },
     { "id" : "Q046", "text" : "Prefer to work by myself, but I know it\'s important to support my coworkers", "dimension" : "COLLABORATION" },
     { "id" : "Q047", "text" : "Have no problem dropping what I\'m doing to help a coworker", "dimension" : "COLLABORATION" },
     { "id" : "Q048", "text" : "For independent projects, I may ask others for their help or suggestions", "dimension" : "COLLABORATION" },
     { "id" : "Q049", "text" : "Tend to avoid projects that require working with others", "dimension" : "COLLABORATION" },
     { "id" : "Q050", "text" : "Keep my emotions under control at work", "dimension" : "COMPOSURE" },
     { "id" : "Q051", "text" : "Feel comfortable with myself in work situations", "dimension" : "COMPOSURE" },
     { "id" : "Q052", "text" : "Stressful events rarely upset me", "dimension" : "COMPOSURE" },
     { "id" : "Q053", "text" : "Will share my distress with others if it is warranted", "dimension" : "COMPOSURE" },
     { "id" : "Q054", "text" : "I express minimal emotions at work", "dimension" : "COMPOSURE" },
     { "id" : "Q055", "text" : "I sometimes feel anxious if tasks don\'t go according to plan", "dimension" : "COMPOSURE" },
     { "id" : "Q056", "text" : "Get overwhelmed by emotions fairly easily", "dimension" : "COMPOSURE" },
     { "id" : "Q057", "text" : "Get stressed out as much as anyone", "dimension" : "COMPOSURE" },
     { "id" : "Q058", "text" : "Am fairly emotional but no more than most people", "dimension" : "COMPOSURE" },
     { "id" : "Q059", "text" : "Stressful situations don\'t really have an effect on me", "dimension" : "COMPOSURE" },
     { "id" : "Q060", "text" : "Have a hard time keeping my emotions under control", "dimension" : "COMPOSURE" },
     { "id" : "Q061", "text" : "Have been known to panic easily", "dimension" : "COMPOSURE" },
     { "id" : "Q062", "text" : "Enjoy brainstorming new solutions to complex problems", "dimension" : "CONCEPTUAL" },
     { "id" : "Q063", "text" : "Prefer to solve problems with facts rather than theories", "dimension" : "CONCEPTUAL" },
     { "id" : "Q064", "text" : "I am as philosophical as the average person", "dimension" : "CONCEPTUAL" },
     { "id" : "Q065", "text" : "Usually use practical approaches, but sometimes more abstract approaches are necessary", "dimension" : "CONCEPTUAL" },
     { "id" : "Q066", "text" : "Prefer intellectually challenging conversations", "dimension" : "CONCEPTUAL" },
     { "id" : "Q067", "text" : "Typically utilize abstract thinking to solve problems", "dimension" : "CONCEPTUAL" },
     { "id" : "Q068", "text" : "Often employ simple, practical solutions", "dimension" : "CONCEPTUAL" },
     { "id" : "Q069", "text" : "Friends look to me to solve complex problems, but not always", "dimension" : "CONCEPTUAL" },
     { "id" : "Q070", "text" : "Complexity sometimes hurts the story line of a movie", "dimension" : "CONCEPTUAL" },
     { "id" : "Q071", "text" : "Think about the big picture, but sometimes I prefer the small details", "dimension" : "CONCEPTUAL" },
     { "id" : "Q072", "text" : "My friends think of me as the creative one", "dimension" : "CONCEPTUAL" },
     { "id" : "Q073", "text" : "When watching or reading murder mysteries, I try to identify the culprit", "dimension" : "CONCEPTUAL" },
     { "id" : "Q074", "text" : "Don\'t see a need for out-of-the-box thinking to solve most problems", "dimension" : "CONCEPTUAL" },
     { "id" : "Q075", "text" : "I am as confident as the average person", "dimension" : "CONFIDENCE" },
     { "id" : "Q076", "text" : "I push for my ideas as much as the average person", "dimension" : "CONFIDENCE" },
     { "id" : "Q077", "text" : "I do not always feel sure of myself", "dimension" : "CONFIDENCE" },
     { "id" : "Q078", "text" : "I would rather celebrate someone else\'s success than my own", "dimension" : "CONFIDENCE" },
     { "id" : "Q079", "text" : "Am somewhat confident when I meet others", "dimension" : "CONFIDENCE" },
     { "id" : "Q080", "text" : "Humility has its importance in life, but so does being confident", "dimension" : "CONFIDENCE" },
     { "id" : "Q081", "text" : "I am no more self-assured than most people", "dimension" : "CONFIDENCE" },
     { "id" : "Q082", "text" : "Go into most situations with an average confidence level", "dimension" : "CONFIDENCE" },
     { "id" : "Q083", "text" : "Am rarely embarrassed because I\'m rarely wrong", "dimension" : "CONFIDENCE" },
     { "id" : "Q084", "text" : "When I do something good, I typically tell others", "dimension" : "CONFIDENCE" },
     { "id" : "Q085", "text" : "Am more humble than most others", "dimension" : "CONFIDENCE" },
     { "id" : "Q086", "text" : "I have average leadership abilities", "dimension" : "DOMINANCE" },
     { "id" : "Q087", "text" : "I lead teams an average amount", "dimension" : "DOMINANCE" },
     { "id" : "Q088", "text" : "I will actively lead if my manager put me in charge", "dimension" : "DOMINANCE" },
     { "id" : "Q089", "text" : "Quick to fill an empty leadership role on a team", "dimension" : "DOMINANCE" },
     { "id" : "Q090", "text" : "I have a desire to advance into leadership", "dimension" : "DOMINANCE" },
     { "id" : "Q091", "text" : "Am not very concerned with having power over others", "dimension" : "DOMINANCE" },
     { "id" : "Q092", "text" : "Speak a lot when in group projects, but let others take the lead", "dimension" : "DOMINANCE" },
     { "id" : "Q093", "text" : "Take an active role in group projects some of the time", "dimension" : "DOMINANCE" },
     { "id" : "Q094", "text" : "Take control of group projects", "dimension" : "DOMINANCE" },
     { "id" : "Q095", "text" : "Let others make decisions unless I have a strong opinion", "dimension" : "DOMINANCE" },
     { "id" : "Q096", "text" : "Give orders to others", "dimension" : "DOMINANCE" },
     { "id" : "Q097", "text" : "Leading by example is just as effective as any other form of leadership", "dimension" : "DOMINANCE" },
     { "id" : "Q098", "text" : "Postpone making decisions if I can", "dimension" : "DRIVE" },
     { "id" : "Q099", "text" : "I push myself to be the best that I can be", "dimension" : "DRIVE" },
     { "id" : "Q100", "text" : "If a project is complex I create a project plan", "dimension" : "DRIVE" },
     { "id" : "Q101", "text" : "I complete what I start unless a big issue arises", "dimension" : "DRIVE" },
     { "id" : "Q102", "text" : "I work until a job is complete", "dimension" : "DRIVE" },
     { "id" : "Q103", "text" : "Exhibit heightened focus on details", "dimension" : "DRIVE" },
     { "id" : "Q104", "text" : "Create flexible deadlines for myself", "dimension" : "DRIVE" },
     { "id" : "Q105", "text" : "Typically achieve the goals I set for myself", "dimension" : "DRIVE" },
     { "id" : "Q106", "text" : "The things I have to do usually get done", "dimension" : "DRIVE" },
     { "id" : "Q107", "text" : "When someone needs to get something done, they assign the task to me", "dimension" : "DRIVE" },
     { "id" : "Q108", "text" : "When assigned a task, I always start on it right away", "dimension" : "DRIVE" },
     { "id" : "Q109", "text" : "Rarely see the need in getting worked up over a deadline", "dimension" : "DRIVE" },
     { "id" : "Q110", "text" : "My positive outlook is average", "dimension" : "OPTIMISM" },
     { "id" : "Q111", "text" : "I have an average ability to anticipate roadblocks", "dimension" : "OPTIMISM" },
     { "id" : "Q112", "text" : "Exhibit an average ability to encourage my teammates", "dimension" : "OPTIMISM" },
     { "id" : "Q113", "text" : "I often try to overcome obstacles, but do not always have the resources to succeed", "dimension" : "OPTIMISM" },
     { "id" : "Q114", "text" : "I keep a good attitude during challenging circumstances except when they become too dire", "dimension" : "OPTIMISM" },
     { "id" : "Q115", "text" : "Maintain a positive attitude in the face of setbacks", "dimension" : "OPTIMISM" },
     { "id" : "Q116", "text" : "Encourage my team with my positive outlook", "dimension" : "OPTIMISM" },
     { "id" : "Q117", "text" : "Am optimistic about my future prospects as much as the average person", "dimension" : "OPTIMISM" },
     { "id" : "Q118", "text" : "Try to stay positive, but sometimes it\'s just not possible", "dimension" : "OPTIMISM" },
     { "id" : "Q119", "text" : "Am somewhat concerned about the future", "dimension" : "OPTIMISM" },
     { "id" : "Q120", "text" : "Remain hopeful even after failure", "dimension" : "OPTIMISM" },
     { "id" : "Q121", "text" : "I consider potential negatives even when a project is going smoothly", "dimension" : "OPTIMISM" },
     { "id" : "Q122", "text" : "Often keep my projects very organized", "dimension" : "ORDER" },
     { "id" : "Q123", "text" : "Enjoy having a variety of tasks", "dimension" : "ORDER" },
     { "id" : "Q124", "text" : "I work well with minimal directions", "dimension" : "ORDER" },
     { "id" : "Q125", "text" : "Typically create loose plans to maintain agility", "dimension" : "ORDER" },
     { "id" : "Q126", "text" : "Am good at keeping everything I have to do straight in my head", "dimension" : "ORDER" },
     { "id" : "Q127", "text" : "See that rules are observed as much as the average person", "dimension" : "ORDER" },
     { "id" : "Q128", "text" : "It\'s important to balance quantity with quality", "dimension" : "ORDER" },
     { "id" : "Q129", "text" : "Create a list of things to do, but only when I\'m very busy", "dimension" : "ORDER" },
     { "id" : "Q130", "text" : "Use \"to-do\" lists whenever I can", "dimension" : "ORDER" },
     { "id" : "Q131", "text" : "Prefer projects that have a clear set of steps to complete", "dimension" : "ORDER" },
     { "id" : "Q132", "text" : "When starting a job, the first thing I do is figure out the rules and procedures", "dimension" : "ORDER" },
     { "id" : "Q133", "text" : "Everything in my room or office has its proper place", "dimension" : "ORDER" },
     { "id" : "Q134", "text" : "Often I share difficult feedback in a frank manner", "dimension" : "SENSITIVITY" },
     { "id" : "Q135", "text" : "Periodically I go out of my way to help others", "dimension" : "SENSITIVITY" },
     { "id" : "Q136", "text" : "Sometimes my colleagues confide in me at work", "dimension" : "SENSITIVITY" },
     { "id" : "Q137", "text" : "Will embrace conflict if the situation requires it", "dimension" : "SENSITIVITY" },
     { "id" : "Q138", "text" : "Usually I provide emotional support to my team", "dimension" : "SENSITIVITY" },
     { "id" : "Q139", "text" : "Think about how my decisions will impact others", "dimension" : "SENSITIVITY" },
     { "id" : "Q140", "text" : "Try to help out others in need, but I don\'t always have the time", "dimension" : "SENSITIVITY" },
     { "id" : "Q141", "text" : "Show compassion for others as much as the average person", "dimension" : "SENSITIVITY" },
     { "id" : "Q142", "text" : "Can sometimes tell if someone is upset", "dimension" : "SENSITIVITY" },
     { "id" : "Q143", "text" : "Provide negative criticisms when necessary, but I don\'t enjoy it", "dimension" : "SENSITIVITY" },
     { "id" : "Q144", "text" : "Can give honest feedback, even if it has to be negative", "dimension" : "SENSITIVITY" },
     { "id" : "Q145", "text" : "Decisions should only be made after considering how they will affect others", "dimension" : "SENSITIVITY" },
     { "id" : "Q146", "text" : "Often introduce myself to new employees", "dimension" : "SOCIABILITY" },
     { "id" : "Q147", "text" : "Enjoy connecting with coworkers an average amount", "dimension" : "SOCIABILITY" },
     { "id" : "Q148", "text" : "After a lot of socializing, I prefer a solitary task", "dimension" : "SOCIABILITY" },
     { "id" : "Q149", "text" : "I try to minimize meetings, but sometimes I need to attend many", "dimension" : "SOCIABILITY" },
     { "id" : "Q150", "text" : "I usually like to attend networking events", "dimension" : "SOCIABILITY" },
     { "id" : "Q151", "text" : "I prefer to keep to myself", "dimension" : "SOCIABILITY" },
     { "id" : "Q152", "text" : "Tend to avoid big gatherings unless it\'s mostly people I know", "dimension" : "SOCIABILITY" },
     { "id" : "Q153", "text" : "Use hand gestures when talking, but only when I\'m excited about the topic", "dimension" : "SOCIABILITY" },
     { "id" : "Q154", "text" : "When in a group, my friends expect me to speak first", "dimension" : "SOCIABILITY" },
     { "id" : "Q155", "text" : "Would rather be with my own thoughts, rather than with people", "dimension" : "SOCIABILITY" },
     { "id" : "Q156", "text" : "Rarely choose to speak up when around a group of people", "dimension" : "SOCIABILITY" },
     { "id" : "Q157", "text" : "Please select \'Not Me\'", "dimension" : "QUALITYASSURANCE" },
     { "id" : "Q158", "text" : "Please swipe left", "dimension" : "QUALITYASSURANCE" },
     { "id" : "Q159", "text" : "Please select \'Me\'", "dimension" : "QUALITYASSURANCE" },
     { "id" : "Q160", "text" : "Please swipe right", "dimension" : "QUALITYASSURANCE" }
   ],
  "pages": [
    {
      "title": "Welcome!",
      "text": "<p>This assessment helps us to understand your <b>workplace styles</b> and <b>behavioral tendencies</b>.</p><p>It typically takes about <b>10 minutes</b> to complete.</p><p>This assessment can be completed on a <b>mobile</b> device just as easily as a <b>computer</b> or <b>laptop</b>.</p>"
    },
    {
      "title": "Ready to Begin?",
      "text": "To ensure you <b>understand how</b> to complete the assessment and so that you have a <b>positive experience</b>, let\'s first go over some <b>important information</b> that’ll help you through this process.",
      "insertright": "st-icon-importantinfo.png"
    },
    {
      "text": "<p>When you begin, you will be shown a deck of cards.</p><p>Each card contains a statement that describes people\'s behaviors, preferences, or tendencies.</p><p>It is your responsibility to respond to each statement by indicating &quot;Me&quot; or &quot;Not Me&quot; as each statement relates to you and your work life.</p>",
      "insertleft": "st-icon-deckofcards.png"
    },
    {
      "text": "<p>You can respond to the statements <b>two</b> different ways.</p><p>The first is by <b>swiping</b> the statement card to the right to respond &quot;Me&quot; or to the left to respond &quot;Not Me&quot;</p>",
      "insertleft": "swipy1.gif"
    },
    {
      "text": "<p>You can also respond by <b>clicking</b> the buttons at the bottom of the screen.</p><p><LJ>Click @match_icon to indicate ‘Me’.</p><p>Click @reject_icon to indicate ‘Not Me’.</p></LJ>",
      "insertleft": "swipy2.gif"
    },
    {
      "title": "Helpful Tips",
      "text": "<LJ><ul><li><b>Focus on work</b>. Try to respond based on how you prefer to or typically behave at work.</li><li>Your <b>first reaction</b> is usually best. Don\'t over-think, just do your best to answer as quickly and honestly as possible.</li><li><b>Make a mistake?</b> You can \'undo\' the last card (only the last card) by selecting the @undo_icon icon.</li><li><b>View instructions throughout.</b> You can select the @info_icon icon to see test instructions at any time during the questionnaire.</li></ul><LJ>"
    },
    {
      "title": "Let\'s Go!",
      "text": "Now that you understand how to complete the assessment, click <b>START</b> when you are ready to begin."
    }
  ],
   "randomize" : true,
"infoText": "Respond by swiping the statement card to the right to respond &quot;Me&quot; or to the left to respond &quot;Not Me&quot;.<br><br>OR<br><br>Click @match_icon to indicate ‘Me’<br>Click @reject_icon to indicate ‘Not Me’",
"finalCardText": "End of the stack, Jack!  You have a few seconds to undo that last card.  If you\'re all set, press \'Finish\' or just wait here to complete this assessment.",
"exitMessage": "Thank you for completing the assessment<br><br>We appreciate your time and effort. Your input has been valuable."
}';
