
words:
	g++ -g -o ttwist ttwist.cpp
tree:
	g++ -g -o ttwist_quicktree ttwist_quicktree.cpp 
wintree:
	g++ -mno-cygwin -g -o ttwist_win ttwist_quicktree.cpp
clean:
	rm -rf ttwist ttwist_output.txt core ttwist_quicktree @>/dev/null

